import React from 'react';
import { BusinessProfile, StrategicAnalysis } from '../types';
import { X, ShieldAlert, Zap, Target, Globe, MapPin, TrendingUp, TrendingDown, Minus, DollarSign, AlertTriangle, Scale, ListChecks, Lightbulb } from 'lucide-react';

interface BusinessOverviewModalProps {
  profile: BusinessProfile;
  analysis: StrategicAnalysis;
  onClose: () => void;
}

export const BusinessOverviewModal: React.FC<BusinessOverviewModalProps> = ({ profile, analysis, onClose }) => {
  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto flex flex-col">
        
        {/* Header */}
        <div className="bg-indigo-900 p-6 flex justify-between items-start text-white sticky top-0 z-10 shadow-md">
          <div>
            <div className="flex gap-2 mb-2">
              <div className="inline-block px-2 py-1 bg-white/10 rounded text-xs font-bold uppercase tracking-wide">
                {analysis.legalStructure || profile.businessType}
              </div>
              <div className="inline-block px-2 py-1 bg-white/10 rounded text-xs font-bold uppercase tracking-wide">
                {profile.targetRegion}
              </div>
            </div>
            <h2 className="text-2xl font-bold leading-tight">Strategic Intelligence</h2>
            <p className="text-indigo-200 text-sm mt-1">{profile.industry} • Generated by TaskAI Modules</p>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-white/20 rounded-full transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="p-6 space-y-6 bg-slate-50">
          
          {/* Sanity Check & Viability Score (Module 2) */}
          <div className="grid md:grid-cols-3 gap-4">
             <div className="md:col-span-2 bg-white p-5 rounded-xl border border-slate-200 shadow-sm">
                <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Sanity Check</h3>
                <p className="text-lg font-medium text-slate-800 italic leading-relaxed">
                  "{analysis.sanityCheck || analysis.elevatorPitch}"
                </p>
             </div>
             <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm flex flex-col justify-center items-center text-center">
                <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Viability Score</h3>
                <div className="relative">
                   <div className={`text-4xl font-black ${
                      (analysis.marketIntelligence.viabilityScore || 0) > 75 ? 'text-emerald-500' : 
                      (analysis.marketIntelligence.viabilityScore || 0) > 50 ? 'text-amber-500' : 'text-red-500'
                   }`}>
                      {analysis.marketIntelligence.viabilityScore || 'N/A'}
                   </div>
                   <div className="text-xs text-slate-400 font-medium">out of 100</div>
                </div>
             </div>
          </div>

          {/* Golden Nuggets (Module 2) */}
          <div className="bg-indigo-50 border border-indigo-100 p-4 rounded-xl">
             <div className="flex items-center gap-2 mb-2">
                <Zap className="w-5 h-5 text-indigo-600" />
                <h3 className="font-bold text-indigo-900">Golden Nuggets (Unfair Advantage)</h3>
              </div>
             <p className="text-indigo-800">{analysis.unfairAdvantage}</p>
          </div>

          {/* Market Intelligence (Module 2) */}
          <div className="p-5 rounded-xl border border-blue-200 bg-white shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                   <MapPin className="w-5 h-5 text-blue-600" />
                   <h3 className="font-bold text-slate-800">Market Intelligence</h3>
                </div>
                {analysis.marketIntelligence.inferredCompetitorCount !== undefined && (
                   <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full font-medium">
                      Est. Competitors: {analysis.marketIntelligence.inferredCompetitorCount}
                   </span>
                )}
              </div>
              
              <div className="space-y-4">
                 {/* Strategic Pivot Alert */}
                 {analysis.marketIntelligence.strategicPivot && (
                    <div className="p-4 rounded-xl border border-amber-200 bg-amber-50">
                         <div className="flex items-center gap-2 mb-2 text-amber-800">
                            <AlertTriangle className="w-5 h-5" />
                            <h3 className="font-bold">Pivot Recommendation</h3>
                         </div>
                         <p className="text-sm text-amber-900 mb-1">
                            <strong>Suggested Location:</strong> {analysis.marketIntelligence.strategicPivot.suggestedLocation}
                         </p>
                         <p className="text-sm text-amber-800 leading-relaxed">
                            {analysis.marketIntelligence.strategicPivot.reasoning}
                         </p>
                    </div>
                  )}

                  {/* Market Gap */}
                  {analysis.marketIntelligence.marketGap && (
                     <div className="p-3 bg-blue-50 rounded-lg border border-blue-100">
                        <p className="text-xs font-bold text-blue-600 uppercase mb-1">Identified Market Gap</p>
                        <p className="text-sm text-blue-900">{analysis.marketIntelligence.marketGap}</p>
                     </div>
                  )}
              </div>
          </div>

          {/* Branding & Legal (Module 3) */}
          <div className="grid md:grid-cols-2 gap-4">
             {/* Branding */}
             <div className="p-4 rounded-xl border border-slate-200 bg-white">
                <div className="flex items-center gap-2 mb-3">
                   <Lightbulb className="w-5 h-5 text-yellow-500" />
                   <h3 className="font-bold text-slate-800">Suggested Names</h3>
                </div>
                <div className="space-y-2">
                   {analysis.suggestedNames?.map((name, i) => (
                      <div key={i} className="px-3 py-2 bg-slate-50 rounded-lg border border-slate-100 text-sm font-medium text-slate-700">
                         {name}
                      </div>
                   ))}
                </div>
             </div>
             
             {/* Legal Structure */}
             <div className="p-4 rounded-xl border border-slate-200 bg-white">
                <div className="flex items-center gap-2 mb-3">
                   <Scale className="w-5 h-5 text-slate-600" />
                   <h3 className="font-bold text-slate-800">Legal Structure</h3>
                </div>
                <div className="text-center p-3 bg-slate-50 rounded-lg border border-slate-100 mb-2">
                   <div className="text-xl font-bold text-slate-800">{analysis.legalStructure}</div>
                </div>
                <p className="text-xs text-slate-500 leading-relaxed">
                   {analysis.legalReasoning}
                </p>
             </div>
          </div>
          
           {/* Financial Feasibility (Module 3) */}
           {analysis.financialFeasibility && (
            <div className="p-5 rounded-xl border border-emerald-100 bg-white shadow-sm">
                <div className="flex items-center gap-2 mb-3">
                    <DollarSign className="w-5 h-5 text-emerald-600" />
                    <h3 className="font-bold text-slate-800">Financial Feasibility (SEK)</h3>
                </div>
                <div className="grid grid-cols-2 gap-4 mb-4">
                    <div className="bg-emerald-50 p-3 rounded-lg border border-emerald-100">
                        <p className="text-xs text-emerald-600 font-semibold uppercase">Startup Cost</p>
                        <p className="text-lg font-bold text-emerald-900">{analysis.financialFeasibility.estimatedStartupCost.toLocaleString()} kr</p>
                    </div>
                    <div className="bg-emerald-50 p-3 rounded-lg border border-emerald-100">
                        <p className="text-xs text-emerald-600 font-semibold uppercase">Monthly Break-even</p>
                        <p className="text-lg font-bold text-emerald-900">{analysis.financialFeasibility.monthlyBreakEvenRevenue.toLocaleString()} kr</p>
                    </div>
                </div>
                <div className="text-sm text-slate-600 bg-slate-50 p-3 rounded-lg">
                    {analysis.financialFeasibility.reasoning}
                </div>
            </div>
           )}

           {/* Setup Checklist (Module 3) */}
           {analysis.setupChecklist && (
              <div className="p-5 rounded-xl border border-slate-200 bg-white">
                 <div className="flex items-center gap-2 mb-3">
                    <ListChecks className="w-5 h-5 text-slate-600" />
                    <h3 className="font-bold text-slate-800">Swedish Setup Checklist</h3>
                 </div>
                 <div className="space-y-2">
                    {analysis.setupChecklist.map((item, i) => (
                       <a 
                          key={i} 
                          href={item.url} 
                          target="_blank" 
                          rel="noreferrer"
                          className="flex items-center justify-between p-3 rounded-lg border border-slate-100 hover:border-indigo-300 hover:bg-indigo-50 transition-all group"
                       >
                          <span className="text-sm text-slate-700 font-medium">{item.task}</span>
                          {item.url && <Globe className="w-4 h-4 text-slate-400 group-hover:text-indigo-600" />}
                       </a>
                    ))}
                 </div>
              </div>
           )}

        </div>
      </div>
    </div>
  );
};